title: Jaswand Docs

email: arkits@outlook.com

description: >- # this means to ignore newlines until "baseurl:"
  Create beautiful reports, right from Java!

baseurl: "/jaswand" # the subpath of your site, e.g. /blog
url: "https://arkits.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ark1ts

github_username:  arkits

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed